### ISSUE TITLE
请问SQL怎样导入

### ISSUE THREAD

**Issue by hanjeahwan** [SUTFutureCoder/paike1.5#1]
我试了导入SQL文件但是导入失败

**Comment by SUTFutureCoder** [comment]
具体提示是什么呢？请确认是mysql数据库

**Comment by hanjeahwan** [comment]
![ad](https://cloud.githubusercontent.com/assets/21311478/19180327/65ca2e40-8c97-11e6-904a-efe13bfa8d5c.JPG)
我导入你里面的paike.sql然后这是结果

**Comment by SUTFutureCoder** [comment]
非常感谢关注这个项目，提示是上传文件大小超过了php.ini限制。请修改/etc/php5/apache/php.ini(应该是这个路径)里面的max_upload......的大小

**Comment by hanjeahwan** [comment]
![ad](https://cloud.githubusercontent.com/assets/21311478/19180484/b17fb1d8-8c98-11e6-9dd8-73e716dd76e3.JPG)
我设置了5mb 也是不行 或许还有其他方法解决吗？

**Comment by SUTFutureCoder** [comment]
更大一些吧，上传完毕再改回来

**Comment by hanjeahwan** [comment]
请问老师的的账号和密码可以给个列子吗？

**Comment by SUTFutureCoder** [comment]
00001

密码是123456

普通教师账号1开头。可以查看下用户表，目前用手机进行回复

**Comment by hanjeahwan** [comment]
![image](https://cloud.githubusercontent.com/assets/21311478/19180855/a6d360e2-8c9b-11e6-95d9-17f9f959511c.png)
不好意思打扰了，想问问过期是什么问题？

**Comment by SUTFutureCoder** [comment]
请登录00001这个账号，密码123456.左侧会有学期初始化，初始化16年即可

**Comment by 6688jingtian** [comment]
哈哈，我来了，学长

**Comment by xibeiyelang** [comment]
出现一个问题，就是服务时间部分会提示一个警告！

**Comment by SUTFutureCoder** [comment]
非常感谢关注这个项目，请问具体警告内容是什么呢？是否有截图？ @xibeiyelang

**Comment by xibeiyelang** [comment]
---

 这个就是截图！还有就是excel导出数据的时候出现错误，和对应的乱码情况！

------------------ 原始邮件 ------------------
发件人: "SUTFutureCoder";notifications@github.com;
发送时间: 2016年11月17日(星期四) 凌晨0:20
收件人: "SUTFutureCoder/paike1.5"paike1.5@noreply.github.com; 
抄送: "鱼"865115598@qq.com; "Mention"mention@noreply.github.com; 
主题: Re: [SUTFutureCoder/paike1.5] 请问SQL怎样导入 (#1)

非常感谢关注这个项目，请问具体警告内容是什么呢？是否有截图？ @xibeiyelang

**Comment by SUTFutureCoder** [comment]
@xibeiyelang 在邮件和github并没有显示错误截图。麻烦重新传一下。
excel导出的时候请贴出错误信息和乱码截图

**Comment by yya454** [comment]
将项目clone到服务器中能访问到的目录（相关技术：安装lamp或lnmp），授予777权限(sudo chmod 777 -R /var/www/html/paike1.5)  请问这个是怎么做的？什么意思。我是小白白白。。。。

**Comment by SUTFutureCoder** [comment]
> 将项目clone到服务器中能访问到的目录（相关技术：安装lamp或lnmp），授予777权限(sudo chmod 777 -R /var/www/html/paike1.5) 请问这个是怎么做的？什么意思。我是小白白白。。。。

如果是本机Linux部署，直接将文件夹放到/var/www/html后打开终端执行命令即可
如果用的是Linux系统的服务器，可以先ssh登录到机器上，然后将文件夹放到/var/www/html后打开终端执行命令
